version: '3.4'

services:
  cheesehub:
    image: ${DOCKER_REGISTRY-}cheesehub
    build:
      context: Cheese
      dockerfile: Dockerfile
    depends_on:
        - sql

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password